# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pool:
  name: "Aida"

steps:
- task: UseDotNet@2
  displayName: use sdk 3.1.x version
  inputs:
    packageType: runtime
    version: 3.1.4

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: build
    projects: 'GameOfLifeAPI.sln'

- task: DotNetCoreCLI@2
  displayName: tests
  inputs:
    command: test
    projects: 'GameOfLife.Tests/GameOfLife.Tests.csproj'
    arguments: '--no-restore --no-build'

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: drop artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop